[package]
version = "1.0.0"
authors =["Robotica"]
title = "Robotica Video Scrubber Example"
description = "An example that demonstrates how to create Video widgets and VideoScrubber widgets using OpenCV and omni.ui.DynamicTextureProvider"
category = "Example"
keywords = ["kit", "example", "video", "scrubber"]
readme  = "docs/README.md"
repository = "https://github.com/md84419/kit-ext-scrubber-experiment"
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.pipapi" = {}
"omni.warp" = {}

[python.pipapi]
requirements = [
    "opencv-python"
]
use_online_index = true

[[python.module]]
name = "robotica.example.video.scrubbing"

# this is a custom setting used in our app setup to choose the Layout
[settings.app]
layout.name = "default"
testMode = false

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
